insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Blennerhassett', 'Somerset', '2022-06-06', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Gumby', 'Tarah', '2022-03-09', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Lemmertz', 'Devin', '2022-07-13', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Durnall', 'Martyn', '2022-06-16', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Jerwood', 'Jesse', '2022-03-26', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('MacArdle', 'Daniele', '2022-02-10', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Semple', 'Petrina', '2022-04-12', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Salandino', 'Arlin', '2022-10-08', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Eastmead', 'Ardelis', '2022-11-12', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Collibear', 'Brice', '2022-08-08', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Yewdell', 'Ida', '2022-08-14', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Tossell', 'Catlaina', '2021-12-21', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Lissandrini', 'Hyman', '2022-06-26', true);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Bozworth', 'Natalina', '2022-06-17', false);
insert into STUDENT (last_Name, first_Name, birth_Date, wants_Newletter) values ('Calkin', 'Martguerita', '2022-02-22', false);
insert into COURSE (title) values ('The Epic of Everest');
insert into COURSE (title) values ('Howl''s Moving Castle (Hauru no ugoku shiro)');
insert into COURSE (title) values ('Steamroller and the Violin, The (Katok i skripka)');
insert into COURSE (title) values ('Last Days on Mars, The');
insert into COURSE (title) values ('Fear[s] of the Dark (Peur[s] du noir)');
insert into COURSE (title) values ('Body/Cialo');
insert into COURSE (title) values ('Predestination');
insert into COURSE (title) values ('The Humanoid');
insert into COURSE (title) values ('Dexter the Dragon & Bumble the Bear (a.k.a. Dragon That Wasn''t (Or Was He?), The) (Als je begrijpt wat ik bedoel)');
insert into COURSE (title) values ('7 Virgins (7 vírgenes)');
insert into COURSE (title) values ('Cry in the Night, A');
insert into COURSE (title) values ('Goddess, The (Shen nu)');
insert into COURSE (title) values ('Eraser');
insert into COURSE (title) values ('Men of Means');
insert into COURSE (title) values ('Forbidden Fruit (Kielletty hedelmä)');
insert into COURSE_STUDENT (course_id, student_id) values (2,3);
insert into COURSE_STUDENT (course_id, student_id) values (2,4);
insert into COURSE_STUDENT (course_id, student_id) values (4,7);
insert into COURSE_STUDENT (course_id, student_id) values (6,9);
insert into COURSE_STUDENT (course_id, student_id) values (7,9);